name: Generate Profile Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Most Used Languages Card
        uses: lowlighter/metrics@latest
        with:
          # This token provides the action permission to write back into your repo
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: top-langs.svg
          output_path: profile/
          base: "" 
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 10
          config_timezone: Asia/Kolkata
          
          # Force the plugin to use the internal GitHub Action token for the push sequence
          committer_token: ${{ secrets.GITHUB_TOKEN }}
